[package]
name = "mysql-passwordless-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hexdump = "0.1.1"
sha1 = "0.10.5"
tokio = { version = "1.29.1", features = ["full"] }
